### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by tawan475** [TimeForANinja/node-ytpl#110]
```
   TypeError: Cannot read property 'map' of undefined
    at Object.exports.parseText (D:\project1\node_modules\ytpl\lib\utils.js:37:73)
    at parseItem (D:\project1\node_modules\ytpl\lib\parseItem.js:24:17)
    at catchAndLogFunc (D:\project1\node_modules\ytpl\lib\parseItem.js:47:12)
    at module.exports (D:\project1\node_modules\ytpl\lib\parseItem.js:70:46)
    at Array.map (<anonymous>)
    at parsePage2 (D:\project1\node_modules\ytpl\lib\main.js:103:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async parsePage2 (D:\project1\node_modules\ytpl\lib\main.js:123:22)
    at async module.exports (D:\project1\node_modules\ytpl\lib\main.js:89:22)
    at async dls (D:\project1\index.js:44:24)
```
    
```
failed at func parseItem: Cannot read property 'map' of undefined
pls post the the files in D:\ytdl-caption\node_modules\ytpl\dumps to https://github.com/TimeForANinja/node-ytpl/issues
os: win32-x64, node.js: v14.5.0, ytpl: 2.1.0
```
[fj3e9g4aeb-1617380721756.txt](https://github.com/TimeForANinja/node-ytpl/files/6250437/fj3e9g4aeb-1617380721756.txt)

**Comment by TimeForANinja** [comment]
how dafuq does a video without title exists....
hate... youtube...
https://www.youtube.com/watch?v=nc1kN8ZSfGQ

**Comment by tawan475** [comment]
> how dafuq does a video without title exists....
> hate... youtube...

Ah yes, Youtube the iceberg

You might prob wanna make a check if some variables are empty
or might make an option to just opt out from getting infos entirely
because you can already do that with `ytdl-core`

**Comment by TimeForANinja** [comment]
gonna push to npm in a bit 👍

**Comment by tawan475** [comment]
Thanks for the fix! 👍
