### ISSUE TITLE
Error thrown when trying to use a channel playlist ID

### ISSUE THREAD

**Issue by OmgImAlexis** [TimeForANinja/node-ytpl#119]
```js
> var ytpl = require('ytpl');
undefined
> ytpl('UU2-i3KuYoODXsM99Z3')
Promise { <pending> }
> (node:92625) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'playlistSidebarRenderer' of undefined
    at module.exports (/Users/xo/code/OmgImAlexis/_/node_modules/ytpl/lib/main.js:29:6)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:92625) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:92625) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TimeForANinja** [comment]
sry for taking a while to reply
i guess they changed the default behaviour
you can even see it if you manually go to the playlist page
https://www.youtube.com/playlist?list=UU2-i3KuYoODXsM99Z3
they don't display an error but redirect to the main page...

so the error block starting [here](https://github.com/TimeForANinja/node-ytpl/blob/master/lib/main.js#L23) basically becomes useless

**Comment by TimeForANinja** [comment]
thanks for letting me know about the error
the new Version should at least produce a clean error
