### ISSUE TITLE
TypeError "listener" arguement must be a function (nodejs v8.17.0)

### ISSUE THREAD

**Issue by Blackhawk-TA** [TimeForANinja/node-ytpl#46]
I'm trying to use the module but I always get the error below. This isn't the case when I use nodejs v12.16.3, but unfortunately I have to use 8.17.0 due to some other dependencies.
Your other node module "ytsr" for searching YouTube videos has the exact same issue.

Steps to reproduce:
- switch to nodejs v8.17.0 (`npm install -g n && n 8.17.0`)
- paste the example code from the readme into a js file
- install the ytpl node module
- run the js file

Error message:
```
events.js:340
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at ClientRequest.once (events.js:340:11)
    at new ClientRequest (_http_client.js:174:10)
    at Object.request (http.js:39:10)
    at Object.request (https.js:245:15)
    at Object.get (https.js:249:21)
    at module.exports (/Users/user/Documents/Coding/test/node_modules/ytpl/lib/firstpage.js:11:25)
    at util.getPlaylistId (/Users/user/Documents/Coding/test/node_modules/ytpl/lib/main.js:38:5)
    at Object.exports.getPlaylistId (/Users/user/Documents/Coding/test/node_modules/ytpl/lib/util.js:90:12)
    at module.exports (/Users/user/Documents/Coding/test/node_modules/ytpl/lib/main.js:35:8)
    at Object.<anonymous> (/Users/user/Documents/Coding/test/test.js:3:1)
```

**Comment by TimeForANinja** [comment]
🤔 they switched from `https.get(options, callback)` to `https.get(url, options, callback)`
wondering why the v8 tests still pass

**Comment by TimeForANinja** [comment]
fixed with rework 👍
