### ISSUE TITLE
Error: Status code: 302

### ISSUE THREAD

**Issue by RaphaelSanti31** [TimeForANinja/node-ytpl#49]
Hello there. It gets the following error. It was working normally but now it gives this error.

Error: Status code: 302
    at ClientRequest.<anonymous> (C:\Users\gani_ipek\Desktop\bot_v2\node_modules\ytpl\lib\firstpage.js:14:23)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by peanutbother** [comment]
same error here.

tried to play with headers to see if I can get another result but it still does not work

what I could find out is, when I patch https://github.com/jabuco/node-ytpl/blob/peanutbother-patch-1/lib/firstpage.js#L13 it seems to give me a more expected result. my problem is a rate limit / code 429 since I issued too many requests. this error did not get through before so I next need to investigate how to circumvent this error

**Comment by TimeForANinja** [comment]
does the response header include any location that makes sense?
