### ISSUE TITLE
Cannot retrieve a playlist page that has no author information

### ISSUE THREAD

**Issue by e-westra** [TimeForANinja/node-ytpl#51]
When trying to retrieve the following playlist https://www.youtube.com/playlist?list=OLAK5uy_msBpY2-SQoKH1j156gHSF_x551BIlrqlY the following error is thrown:

```D:\Projects\Kissa\discord-bot\node_modules\ytpl\lib\util.js:25
    total_items: Number(authorMatch[2].replace(/\D/g, '')),
                                   ^

TypeError: Cannot read property '2' of null
    at Object.exports.getGeneralInfo (D:\Projects\Kissa\discord-bot\node_modules\ytpl\lib\util.js:25:36)
    at IncomingMessage.<anonymous> (D:\Projects\Kissa\discord-bot\node_modules\ytpl\lib\firstpage.js:30:29)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
The issue seems to be because the playlist page does not contain information about the author/channel. Should these types of playlists be supported?

**Comment by TimeForANinja** [comment]
supported yes
didn't exist when i first wrote ytpl
guess i'd expect author related information to be null in such a case

busy for about another 2 weeks until i could personally look into it
