### ISSUE TITLE
Problem with ytpl not working on any playlists.

### ISSUE THREAD

**Issue by icedTet** [TimeForANinja/node-ytpl#58]
Every time I try and use ytpl it errors out saying :
D:\Stuff\TetTicket\node_modules\ytpl\lib\util.js:22
    title: exports.removeHtml(importantTxt.match(PLAYLIST_NAME_REGEXP)[1]),
                                                                      ^

```
TypeError: Cannot read property '1' of null
    at Object.exports.getGeneralInfo (D:\Stuff\TetTicket\node_modules\ytpl\lib\util.js:22:71)
    at IncomingMessage.<anonymous> (D:\Stuff\TetTicket\node_modules\ytpl\lib\firstpage.js:30:29)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-1337-bot@0.0.1 start: node server.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-1337-bot@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\theco\AppData\Roaming\npm-cache_logs\2020-07-16T07_06_35_026Z-debug.log
```

**Comment by iquantime** [comment]
I am having the same problem

**Comment by talmobi** [comment]
A temporary fix is to use a different user-agent for node-ytpl:

goto `node_modules/ytpl/lib/main.js`

and change the user-agent to this:

```js
const DEFAULT_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.100.0'; // eslint-disable-line max-len
```

**Comment by TacoTuesday203** [comment]
> A temporary fix is to use a different user-agent for node-ytpl:
> 
> goto `node_modules/ytpl/lib/main.js`
> 
> and change the user-agent to this:
> 
> ```js
> const DEFAULT_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.100.0'; // eslint-disable-line max-len
> ```

I changed the user agent in main.js, but this triggered another error.

``` 
pos = haystack.indexOf(left);
                 ^
TypeError: Cannot read property 'indexOf' of undefined
    at Object.exports.between (C:\Users\Josh\Desktop\Discord\JahBot\node_modules\ytpl\lib\util.js:148:18)
    at IncomingMessage.<anonymous> (C:\Users\Josh\Desktop\Discord\JahBot\node_modules\ytpl\lib\nonfirstpage.js:22:45)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1226:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Any recommendations?
