### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by TheSpartaPT** [TimeForANinja/node-ytpl#75]
Hello, i've been getting this issue latelly 100% of the time i try to use your lib
```
TypeError: Cannot read property '1' of null
    at Object.exports.getGeneralInfo ({INSERT_PROJECT_FOLDER_HERE}/node_modules/ytpl/lib/util.js:22:71)
    at IncomingMessage.<anonymous> ({INSERT_PROJECT_FOLDER_HERE}/node_modules/ytpl/lib/firstpage.js:30:29)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
this is the piece of code where i use your lib:

```js
ytpl(playlistId, (err, result) => {
	if(err) {
		console.log(err);
	}else {
		...{DATA_PROCESSING_FOR_WHAT_COMES_INSIDE_THE_result_VAR}...
	}
});
```

the variable `playlistId` contains the id of the playlist found on every youtube playlist URL GET parameter "list".

**Comment by TimeForANinja** [comment]
would be cool to know if this is still a problem with the rework 🤔

**Comment by TheSpartaPT** [comment]
just tested it, still a problem yes

**Comment by TimeForANinja** [comment]
> just tested it, still a problem yes

can you send another error stack?

**Comment by TheSpartaPT** [comment]
sorry, completly forgot to reply to your request
i tested it further and got it to stop throwing an error stack (idk what was going on with pm2 but somehow pm2 restart *id* wasn't really working and led me to believe it was still throwing an error stack)

it still isn't working though, i'll get back to you when i find something because now there isn't any errors to go by

**Comment by LamkasDev** [comment]
i can confirm this is still happening to me

```
TypeError: Cannot read property '1' of null
    at Object.exports.getGeneralInfo ({project}\node_modules\ytpl\lib\util.js:22:71)
    at IncomingMessage.<anonymous> ({project}\node_modules\ytpl\lib\firstpage.js:30:29)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by TimeForANinja** [comment]
🤔 that doesn't look like rework
you sure you're on v1.0.0?

**Comment by LamkasDev** [comment]
oh yeah npm didn't update the version correctly, so i had to uninstall and install again the package manually. thanks ❤️

**Comment by TimeForANinja** [comment]
sounds solved 👍
